language: android
jdk: oraclejdk8
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - build-tools-25.0.0
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support

    # The BuildTools version used by your project
    # - build-tools-25.0.0

    # The SDK version used to compile your project
    - android-25

    # Additional components
    # - extra-google-google_play_services
    # - extra-google-m2repository
    # - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-17
    - sys-img-armeabi-v7a-android-25

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
 - chmod +x gradlew
 
notifications:
  email:
    on_success: always
    on_failure: never
